/**
 * Easing function for determining the shape of the image
 * @param {number} x
 * @returns {number}
 */
function easeInQuart(x) {
    return x * x * x * x;
}

/**
 * Transforms the blob generated by the generate_interact_images function into a base64 format which can be used for textures.
 * @param {Blob} blob
 * @returns {Promise}
 */
function blobToBase64(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result); // Returns the full Data URL
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

/** 
* Generates a set of images to be used as textures when approaching or going away from the interact point.
* @param {Object} options
* @param {string} options.background
* @param {string} options.border
* @param {string} options.color
* @param {string} options.key
*/
function generate_interact_images(options = {
    background: "#26282c",
    border: "#363940",
    color: "#a6a7ab",
    key: "E"
}) {

    return new Promise((resolve, reject) => {
        const images = [];

        const steps = 16;

        let canvas = new OffscreenCanvas(128, 128);

        let ctx = canvas.getContext("2d");


        // Wait to get context
        while(!ctx){
            console.log("Waiting for context...");
            ctx = canvas.getContext("2d");
        }

        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = "high";

        for(let i = 0; i <= steps; i++){
            const progress = easeInQuart(i / steps);

            const [radius_min, radius_max] = [16, 48];
            const radius = radius_min + (radius_max - radius_min) * progress;

            ctx.clearRect(0, 0, canvas.width, canvas.height);
            ctx.fillStyle = options.background;
            ctx.strokeStyle = options.border;

            ctx.beginPath();
            ctx.roundRect((128-96)/2, (128-96)/2, 96, 96, radius);
            ctx.lineWidth = 6;
            ctx.stroke();
            ctx.fill();

            ctx.strokeStyle = options.border;
            ctx.roundRect((128-96)/2, (128-96)/2, 96, 90 + 6*progress, radius);
            ctx.lineWidth = 6;
            ctx.stroke();

            let opacity = 0xff * progress;
            let text_opacity = 0xff - (0xff * progress);

            if(opacity <= 0x0f) opacity = 0x00;
            if(text_opacity <= 0xf0) text_opacity = 0x00;

            ctx.font = "700 48px Arial";
            ctx.textBaseline = "middle";
            ctx.textAlign = "center";
            ctx.fillStyle = options.color + Math.round(text_opacity).toString(16).padStart(2, "0");
            ctx.fillText(options.key, 128/2, 128/2);

            ctx.transform(1, 0, 0, 1, 40, 42);
            
            const lightbulb = new Path2D("M6 18a18 18 0 1 1 30.522 12.93c-0.609 0.588 -1.077 1.2 -1.359 1.857l-2.286 5.307A1.5 1.5 0 0 1 31.5 39h-15a1.5 1.5 0 0 1 -1.38 -0.906l-2.283 -5.31a6 6 0 0 0 -1.359 -1.854A17.94 17.94 0 0 1 6 18m9 25.5a1.5 1.5 0 0 1 1.5 -1.5h15a1.5 1.5 0 0 1 0 3l-0.672 1.341a3 3 0 0 1 -2.682 1.659H19.854a3 3 0 0 1 -2.682 -1.659L16.5 45a1.5 1.5 0 0 1 -1.5 -1.5");

            ctx.fillStyle = options.color + Math.round(opacity).toString(16).padStart(2, "0");

            ctx.fill(lightbulb, "evenodd");

            ctx.resetTransform();   

            canvas.convertToBlob().then((image) => {
                blobToBase64(image).then(b64 => {
                    images.push(b64);
                    
                    if(i == steps){
                        canvas.width = 0;
                        canvas.height = 0;
                        canvas = null;
                        ctx = null;

                        resolve(images);
                    }
                })
            });
        }
    })
}


window.addEventListener("message", (event) => {
    if(event.data.action === 'get_interact_images'){
        generate_interact_images(event.data.options).then((images) => {
            fetch("https://cd_bridge/interact_images", {
                method: "POST",
                body: JSON.stringify({
                    images: images,
                    unique_id: event.data.unique_id
                })
            }).catch(e => console.error(e));
        });  
    }
})